[functions]
  directory = "netlify/functions"
  timeout = 26

[[headers]]
  for = "/tools/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
